server.port=7777

# Application name
spring.application.name=amaddaDB

# Data source
spring.jpa.show-sql=true
spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://db-pnbr4-kr.vpc-pub-cdb.ntruss.com/amattaDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=amadda
spring.datasource.password=qwer1234!


# JPA 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# spring.web.resources.static-locations=file:/C:/finalproject/AMADDA-PROJECT-BACK/src/main/resources/static/img/profile
#경로 설정 (mypage >  UserController, fileService )
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# open api
# 공휴일 서비스
openApi.serviceKey=41DV3vcUtHn4Is4xrdQzTyBerRXL7FAfgdFHAcBitc7GNTs%2BXUAO5wbbaIMM%2BvoZxN6EH4L8BcNUcPuWH8YkiQ%3D%3D
openApi.callBackUrl=http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo
openApi.dataType=XML

mybatis.mapper-locations=mappers/*.xml

# 카멜과 스네이크 방식 매핑 설정
mybatis.configuration.map-underscore-to-camel-case=true

#박정민이 추가한 거

#log로 디버깅 하는 용
# logging.level.root=INFO
# logging.file.name=logs/info.log
# logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

#kakaoAPI
kakao.client_id=23304600577fdd471ad2916f0d2ec5bf
kakao.redirect_uri=http://localhost:7777/callback
app.main_page_url=http://localhost:7777/amadda

#jwt 시크릿코드
jwt.secret=XrduGIBXpwUrD6Ls0nHY242YHwy1rqcnSOqQQm51aNH9uDBDEEpc/OOZ9hXi7RYvN2vprtVRWKyBrqYcT0KtIQ==

#디버깅
logging.level.org.apache.coyote.http11.Http11Processor=DEBUG

#결제 키
iamport.api_key=5014340734058557
iamport.api_secret=YzKqiChf7CfHtXBv1aQnBGf50AhVneecqUAXX6oPwYicbTQRJXRaxNJvjMT9ExEAqMX0lPiIHFZL9c6g


#naver cloud object storage 키 by 채은
spring.naver.cloud.bucket=amadda.post.image
file.upload-dir=food-images
spring.s3.accessKey=ncp_iam_BPASKR13MnoXP45CL3jt
spring.s3.secretKey=ncp_iam_BPKSKR8wOYHGXpLcbzRAJoEMFznWDZKi8u


#기상청 API 서비스 키 by 원준
weather.service.key= 3XrEdg36ky0UjfGYgqIc5tZO%2FgDCrp6vOPzZEQHAcWUHYnugaIAlpzOOjRIzXHYXAawxFh5%2B1u1j2IrKl74%2FtA%3D%3D
weather.api.url= 	http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtFcst

#날씨 키 by 윤성님
weather.api.key=6579c5fe59caa6e99be282f39b8d2d3e
weather.callBackUrl=https://api.openweathermap.org/data/2.5/forecast
